version: '3.4'

services:
  medicalattention_api:
    image: ${DOCKER_REGISTRY-}medicalattentionapi
    build:
      context: .
      dockerfile: MedicalAttention_API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=172.31.224.1;Port=5432;Database=Medical_DB;Username=postgres;Password=newPostgresql;Pooling=false;
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Medical_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPostgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: